name: macos

on:
  push:
  pull_request:
  schedule:
    - cron: '0 7 * * SUN'

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: macos-12
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3
      - name: Checkout OpenDDS
        uses: actions/checkout@v3
        with:
          repository: OpenDDS/OpenDDS
          path: OpenDDS
          ref: latest-release
      - name: Get OpenDDS git commit
        run: |
          echo OPENDDS_COMMIT=$(cd OpenDDS; git rev-parse HEAD) >> $GITHUB_ENV
      - name: Cache OpenDDS
        id: cache-artifact
        uses: actions/cache@v3
        with:
          path: OpenDDS
          key: c01_${{ matrix.os }}_OpenDDS_${{ env.OPENDDS_COMMIT }}
      - name: Configure OpenDDS
        if: steps.cache-artifact.outputs.cache-hit != 'true'
        run: |
          cd OpenDDS
          ./configure -v --java=$JAVA_HOME_17_X64 --mpcopts="-workers 4"
          tools/scripts/show_build_config.pl
      - name: Compile OpenDDS
        if: steps.cache-artifact.outputs.cache-hit != 'true'
        run: |
          make -C OpenDDS -sj6
      - name: Compile Project IDL
        run: |
          . OpenDDS/setenv.sh
          cd idl
          ./build-libs.sh
      - name: Compile Publisher and Subscriber
        run: |
          . OpenDDS/setenv.sh
          cd pub
          ../build-app.sh
          cd ../sub
          ../build-app.sh
      - name: Run Example
        run: |
          PATH=$JAVA_HOME_17_X64/bin:$PATH
          (cd sub; ./run.sh) &
          (cd pub; ./run.sh Hello)
