name: windows

on:
  push:
  pull_request:
  schedule:
    - cron: '0 7 * * SUN'

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-2022
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}
    defaults:
      run:
        shell: cmd
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3
      - name: Checkout OpenDDS
        uses: actions/checkout@v3
        with:
          repository: objectcomputing/OpenDDS
          path: OpenDDS
          ref: latest-release
      - name: Get OpenDDS git commit
        run: |
          cd OpenDDS
          for /f %%x in ('git rev-parse HEAD') do @echo OPENDDS_COMMIT=%%x>> %GITHUB_ENV%
      - name: Cache OpenDDS
        id: cache-artifact
        uses: actions/cache@v3
        with:
          path: OpenDDS
          key: c02_${{ matrix.os }}_OpenDDS_${{ env.OPENDDS_COMMIT }}
      - name: set up msvc env
        uses: ilammy/msvc-dev-cmd@v1
      - name: Configure OpenDDS
        if: steps.cache-artifact.outputs.cache-hit != 'true'
        run: |
          cd OpenDDS
          call configure -v --java --mpcopts="-workers 4"
          tools\scripts\show_build_config.pl
      - name: Compile OpenDDS
        if: steps.cache-artifact.outputs.cache-hit != 'true'
        run: |
          cd OpenDDS
          call setenv
          msbuild -p:Configuration=Debug,Platform=x64 -m DDS_TAOv2.sln
      - name: Compile Project IDL
        run: |
          call OpenDDS\setenv
          cd idl
          call build-libs
      - name: Compile Publisher
        if: false
        run: |
          . OpenDDS/setenv.sh
          cd pub
          ./build.sh
      - name: Compile Subscriber
        if: false
        run: |
          . OpenDDS/setenv.sh
          cd sub
          ./build.sh
